### ISSUE TITLE
Adding a scheme to a url without scheme results in wrong url

### ISSUE THREAD

**Issue by shashankkr9** [gruns/furl#117]
Example:

```python
url = "google.com"
furled_url = furl(url)
furled_url.scheme = furled_url.scheme or "https"
normalized_url = furled_url.url

# normalized_url is https:///google.com instead of http://google.com
```

**Comment by gruns** [comment]
While initially a head scratcher, this is actually expected behavior. See https://github.com/gruns/furl/issues/103#issuecomment-418843869 and https://github.com/gruns/furl/issues/106#issuecomment-420818489.

This will be resolved with the addition of #110 

Does that answer your question?

Thanks so much, Shashank. Don't hesitate to let me know if there's anything else I can answer.

**Comment by gruns** [comment]
@shashank-iitj: Little bump -- while initially a bit confusing, do the aforementioned Issues and comments clear things up?

For now, at least, until #110 is implemented.

**Comment by gruns** [comment]
closing this pending #110's implementation
