### ISSUE TITLE
furl produces invalid urls

### ISSUE THREAD

**Issue by max-pfeiffer** [gruns/furl#85]
Using the new version 1.0.0, to reproduce:

```python
from furl import furl
test = furl('www.example.com').set(scheme='http').add(path='test/path')
print(test.url)
http:///www.example.com/test/path
```

Notice the three forward slashes "///" in front of the domain.

**Comment by gruns** [comment]
Furl is doing the correct thing here, though it can be slightly confusing at
first glance.

The confusion boils down to how -- in the absense of URL delimiters (e.g. `://`,
`/`, `?`, etc) -- solitary strings like `www.example.com` are parsed.

While `www.example.com` looks like a host to you and me, how does furl know it's
a host? What about

```python
>>> furl('snakes')
```

Is `snakes` a host, too? Or is it a path? Remember host strings can be almost
anything -- they don't need to contain periods (e.g. `localhost`). That, and
every valid host string is also a valid path segment.
`http://foo.com/url/www.example.com/` is a perfectly valid URL, too.

So, to be consistent, furl parses all single-component strings (strings without
multiple URL components separated by URL delimiters) as path strings. You can
see this behavior with `www.example.com` above.

```python
>>> f = furl('www.example.com')
>>> f.host
None
>>> f.path.segments
['www.example.com']
```

This is also exactly the behavior of Python's [urlparse](https://docs.python.org/2/library/urlparse.html) module, too.

```python
>>> from urlparse import urlparse
>>> urlparse('www.example.com')
ParseResult(scheme='', netloc='', path='www.example.com', params='', query='', fragment='')
```

Back to your original example. There are three slashes (`///`) in the final URL
because `www.example.com` is parsed as a path segment and not a host.

```python
>>> f = furl('www.example.com').set(scheme='http').add(path='test/path')
>>> f.path.segments
['www.example.com', 'test', 'path']
>>> f.host
None
```

If you want furl to adopt `www.example.com` as the host, explicitly set it as
the host with `set()`. Like

```python
>>> f = furl().set(host='www.example.com', scheme='http').add(path='test/path')
>>> f.path.segments
['test', 'path']
>>> f.host
'www.example.com'
```

I've thought about adding the ability for furl to 'guess' whether a solitary
string is the host string or a path segment based on whether or not that string
contains periods, but that would lead to inconsistent behavior. Consistent
behavior, even if sometimes initially surprising, is better behavior.

Does that answer your original question?

**Comment by max-pfeiffer** [comment]
Yes, absolutely. Thanks a lot for your very comprehensive answer.

**Comment by gruns** [comment]
Wonderful.

Thank you for bringing this question to my attention, Max. Don't hesitate to let
me know if there's anything I can do for you.
