### ISSUE TITLE
Remove ':' from INVALID_DOMAIN_CHARS

### ISSUE THREAD

**Issue by arcsector** [gruns/furl#92]
Hello there,

First off, great product. It's fantastic and I love it. I'm curious if you can remove `:` from the list of invalid domain characters; we use it to forward all traffic to uncommon ports in order to mitigate probes. Would that be possible? The definition is in `furl.py` on [line 164](https://github.com/gruns/furl/blob/master/furl/furl.py#L164). 

Thank you so much!

**Comment by gruns** [comment]
Can you provide an example of a host string that contains a colon (`:`) which
you'd like furl to consider valid?

An example would be helpful because, if I understand you correctly, removing `:`
from `INVALID_DOMAIN_CHARS` would break furl's adherence to URL standards.
Hostnames aren't allowed to contain colons, dating all the way back to the
original [RFC 952](https://tools.ietf.org/html/rfc952).

```
1. A "name" (Net, Host, Gateway, or Domain name) is a text string up
   to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
   sign (-), and period (.).
```

[RFC 1123](https://tools.ietf.org/html/rfc1123) expanded on this hostname format to allow the first character of a
domain label to start with a numeric (0..9), but colons remained prohibited.

```
2.1  Host Names and Numbers

   The syntax of a legal Internet host name was specified in RFC-952
   [DNS:4].  One aspect of host name syntax is hereby changed: the
   restriction on the first character is relaxed to allow either a
   letter or a digit.
```

The prohibition of colons in host strings also makes intuitive sense: the first
colon, if present, serves as a delimiter that separates the host from the port
(e.g. `host:port`). If colons are permitted in the host, it becomes ambiguous
whether the token after a `:` is a domain label or a port. For example, if `:`
is allowed to appear in host strings, consider the URL

```
http://host:443/
```

Is `443` a domain label, which can start with a numeric character 0..9, or the
port 443? It's ambiguous.

**Comment by arcsector** [comment]
Then maybe allow two colons in the hostname instead of 1, and just assume the numbers after the 2nd are the port? Either way, I removed it from my local copy and it works fine for what I'm using it for. Thanks for the info! You can close this if you want.

**Comment by gruns** [comment]
Wonderful to hear you found a solution that works for you.

Just be cognizant of the fact that URLs in which the host contains a `:` are
non-standard URLs and will be incorrectly parsed by other software that, like
furl, adhere's to the URL standards (RFC 3986, etc).

Thanks again George. Don't hesitate to let me know if there's anything else I
can do for you.
